### ISSUE TITLE
Formatting errors and improvements to pactus.org homepage

### ISSUE THREAD

**Issue by Mr-HoDL58** [pactus-project/pactus.org#131]
It has come to my attention that all the buttons on the mainpage https://pactus.org/ have the text offset to the bottom of the button. It would be good if this can be centralised so there is no offset. I have attatched image to show this formatting issue You will see from the image the text is offset to the bottom.
![offset](https://github.com/pactus-project/pactus.org/assets/148651614/a47258b5-11e9-4905-93ed-97748171a45a)

I also think that the format could do with a small revamp to centralise the text with the buttons. I have attached an edited example of what I mean, it will not be 100% accurate but you will get the idea of the changes. This would just be an improvement suggestion and not neccassarily implemented.
![Edits](https://github.com/pactus-project/pactus.org/assets/148651614/54d36805-60de-4bf0-bb2a-2fefaf7dd807)

**Comment by b00f** [comment]
Good find, @Mr-HoDL58 .
Thanks for reporting the issues and providing details and pictures.

**Comment by Mr-HoDL58** [comment]
This has been resolved.
